FROM mintplexlabs/anythingllm:latest

ENV STORAGE_DIR=/app/server/storage
ENV LLM_PROVIDER=openai-generic
ENV LLM_BASE_URL=https://vllm-api.placeholderdomain.com
ENV EMBEDDING_BASE_URL=https://embed-api.placeholderdomain.com