replicaCount: 1

image:
  repository: cloudflare/cloudflared
  tag: latest
  pullPolicy: IfNotPresent

existingSecretName: cloudflared-tunnel-token
existingSecretKey: token

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

metricsPort: 2000